//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carpool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public int ifr_id { get; set; }
        public int ifr_from_usr_id { get; set; }
        public int ifr_to_usr_id { get; set; }
    
        public virtual User user_usr { get; set; }
        public virtual User user_usr1 { get; set; }
    }
}
