//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carpool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joins
    {
        public int joi_id { get; set; }
        public System.DateTime joi_date { get; set; }
        public int joi_usr_id { get; set; }
        public int joi_tri_id { get; set; }
    
        public virtual Trip trip_tri { get; set; }
        public virtual User user_usr { get; set; }
    }
}
