//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carpool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joins
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }
        public int TripId { get; set; }
    
        public virtual Trip Trip { get; set; }
        public virtual User User { get; set; }
    }
}
