//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carpool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.joins_joi = new HashSet<Joins>();
        }
    
        public int tri_id { get; set; }
        public int tri_number_of_places { get; set; }
        public decimal tri_price { get; set; }
        public Nullable<bool> tri_is_routine { get; set; }
        public decimal tri_period { get; set; }
        public System.DateTime tri_beginning { get; set; }
        public System.DateTime tri_closing { get; set; }
        public int tri_duration { get; set; }
        public int tri_add_id { get; set; }
    
        public virtual Address address_add { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Joins> joins_joi { get; set; }
    }
}
